name: Build and Push demo-app

on:
  push:
    branches:
      - main
      
jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        defaults:
          run:
            working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Log Github Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build
        run: docker build -t ghcr.io/${{ github.repository }}/demo-app:latest .
      
      - name: Push
        run: docker push ghcr.io/${{ github.repository }}/demo-app:latest
